### ISSUE TITLE
"Several files providing this module"

### ISSUE THREAD

**Issue by johngoren** [rajsuvariya/autocompletetextview#1]
Thanks for this module. When I install it, however, the dependencies throw an error. "Tries to require react-native, but there are several files providing this module." Is there something we can fix in Package.json?

<img width="228" alt="screen shot 2017-10-17 at 17 36 09" src="https://user-images.githubusercontent.com/748214/31677115-b7d5df3a-b361-11e7-8585-0d209371d6c8.png">

**Comment by rajsuvariya1** [comment]
@johngoren Thanks for reporting this issue. 
There are few things I would like to highlight here. 
- If you are installing it via npm then there might be some issues as it was not properly pushed to npm.
- I haven't updated this module in a while now. It is using an old version of React Native and that's why I am not so sure why this is failing to find react-native. 

Ad-hoc Solution: If you want to use this module just do one thing. Clone this repo and copy-paste required files, it will work as expected.

Also, I am too busy these days to update this module to the latest version and fix the npm issue if you would like to contribute you are most welcomed.

**Comment by rajsuvariya** [comment]
@johngoren Thanks for reporting this issue.
There are few things I would like to highlight here.

If you are installing it via npm then there might be some issues as it was not properly pushed to npm.
I haven't updated this module in a while now. It is using an old version of React Native and that's why I am not so sure why this is failing to find react-native.
Ad-hoc Solution: If you want to use this module just do one thing. Clone this repo and copy-paste required files, it will work as expected.

Also, I am too busy these days to update this module to the latest version and fix the npm issue if you would like to contribute you are most welcomed.

**Comment by rajsuvariya** [comment]
Hi @johngoren check out this branch. https://github.com/rajsuvariya/autocompletetextview/tree/development

I have solved almost all the issues. Follow the installation guide and let me know in case of any issues.

**Comment by rajsuvariya** [comment]
This is fixed now you can use the npm version as well. Open a new issue in case of any problem you face.
